apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpa-extender
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vpa-extender-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vpa-extender-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: vpa-extender
  namespace: my-operator-project
roleRef:
  kind: ClusterRole
  name: vpa-extender-cluster-role
  apiGroup: rbac.authorization.k8s.io
