---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: namespacemonitors.{{ .Values.domain }}
spec:
  group: {{ .Values.domain }}
  names:
    kind: NamespaceMonitor
    listKind: NamespaceMonitorList
    plural: namespacemonitors
    singular: namespacemonitor
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                  description: The namespace to monitor.

